# Generated by Django 5.0.6 on 2024-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.URLField(max_length=500),
        ),
    ]
