# Generated by Django 5.0.6 on 2024-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
